name: Deploy Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    #- name: Run tests
    #- run: pytest
    
    - name: Package Lambda functions
      run: |
        mkdir -p dist
        
        # Geolocation Lambda
        mkdir -p build/geolocation
        cp -r lambda/geolocation/* build/geolocation/
        pip install -r lambda/geolocation/requirements.txt -t build/geolocation/
        cd build/geolocation && zip -r ../../dist/geolocation.zip . && cd ../..
        
        # Audio Generation Lambda
        mkdir -p build/audio-generation
        cp -r lambda/audio-generation/* build/audio-generation/
        pip install -r lambda/audio-generation/requirements.txt -t build/audio-generation/
        cd build/audio-generation && zip -r ../../dist/audio-generation.zip . && cd ../..
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Upload Lambda packages to S3
      run: |
        aws s3 sync dist/ s3://${{ secrets.LAMBDA_BUCKET }}/
        
    - name: Trigger Infrastructure Deployment
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: trigger-infra-deploy